version: '3.6'
services:
  server:
    build:
      context: ./
    command: npm run start
    ports:
      - "8084:3000"
    environment:
      NODE_ENV: production

  influxdb:
    image: arm32v7/influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
      - influxdb_config:/etc/influxdb
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=iot_power_meter
     
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1234  #change the password
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '43000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  default:
    external:
      name: external-iot-power-meter

volumes:
  grafana_data:
  influxdb_data:
  influxdb_config:

