version: '3.3'
services:
  app:
    build:
      context: ./
    ports:
      - "8085:80"
    volumes:
      - ./dist:/usr/share/nginx/html

networks:
  default:
    external:
      name: external-iot-power-meter
